---
- hosts: webservers
  become: true
  gather_facts: False
  tasks:
    -  name: Make sure we can connect
       ping:
       tags:
         - connection

    -  name: Creation of users
       user:
            name: Freddy
            password: "{{'Yfredd2013' | password_hash('sha512')}}"
            state: present
       tags:
         - users_creation

- hosts: webservers
  become: true
  gather_facts: False
  tasks:
    - name: Creating file, setting permissions and gid bit
      file:
        path: /root/Freddy_file
        owner: Freddy
        group: Freddy
        mode: '2760'
        state: touch
      tags:
        - users_file

- hosts: webservers
  become: true
  gather_facts: False
  tasks:
    - name: Archiving the '/etc' directory on the webservers
      archive:
        path: /etc
        dest: /root/etc.tar.bz2
        format: bz2
      tags:
        - archives


- hosts: tor
  become: true
  gather_facts: False
  tasks:
    -  name: Installing Services on the Tor (CentOS)
       yum:
         name: ['httpd','httpd-devel','mysql','mysql-server','mysql-devel','php','php-devel','php-mysqlnd']
         state: present
       tags:
         - ins_serv_Cent

    -  name: Starting services on the Tor (CentOS)
       service: name={{ item }} state=started enabled=yes
       with_items:
         - httpd
         - mysqld
       tags:
         - turn_on_serv_Cent

- hosts: spine
  become: true
  gather_facts: False
  tasks:
    -  name: Installing Services on the Spine (Debian)
       apt:
         name: ['mariadb-server','mariadb-common','nginx']
         state: present
         update_cache: yes
       tags:
         - ins_serv_Deb

    -  name: Starting services on the Spine (Debian)
       service: name={{ item }} state=started enabled=yes
       with_items:
         - nginx
         - mariadb
       tags:
         - turn_on_serv_Deb

- hosts: webservers
  become: true
  gather_facts: False
  tasks:
    - name: Creating  directory on webservers
      file:
        path: /web/html
        state: directory
      tags:
        - webservers_directory

    - name: Creating a testing group on webservers
      group:
        name: testing
        state: present
      tags:
        - group_creation

- hosts: tor
  become: true
  gather_facts: False
  tasks:
    - name: Creating a network group on Tor (CentOS)
      group:
        name: networks
        state: present
      tags:
        - group_creation
- hosts:
  - webservers
  - spine
  become: true
  gather_facts: False
  tasks:
    - name: Configuring MOTD on webservers nodes
      copy:
        content: "Welcome to webserver node\n"
        dest: /etc/motd
      when: inventory_hostname in groups['webservers']
      tags:
        - setting_motd

    - name: Installing more packages on the TOR (centosnode)
      yum:
        name: ['samba', nfs-utils]
        state: present
      when: inventory_hostname in groups ['tor']
      tags:
        - more_packages
- hosts: webservers
  become: true
  gather_facts: False
  vars_files:
    - userdetails.yml
    - password.yml
  tasks:
    - name: Creating more users on webservers nodes if conditions are department
      user:
        name: "{{ item.username}}"
        password: "{{lisa_password | password_hash('sha512')}}"
        groups: testing
      when: "item.department == 'Software developer' and inventory_hostname in groups['webservers']"
      loop: "{{users}}"
      tags:
        - more_users_creation

    - name: Creating more users on the TOR if conditions are met
      user:
        name: "{{item.username}}"
        password: "{{bob_password | password_hash('sha512')}}"
        groups: Freddy
      when: "item.department == 'Testing' and inventory_hostname in groups['tor']"
      loop: "{{users}}"
      tags:
        - more_users_creation

    - name: Creating more users on all managed nodes
      user:
        name: "{{item.username}}"
        password: "{{lara_password | password_hash('sha512')}}"
      when: item.department == 'HR'
      loop: "{{users}}"
      tags:
        - more_users_creation
